### PR TITLE
Fix `sort_nodes` crash on nodes with symbol names

### LINKED ISSUE #593: ArgumentError: comparison of Array with Array failed
I'm getting the following error on a fairly large rails project when running `tapioca dsl`:

```
/.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'Enumerable#sort_by': ArgumentError: comparison of Array with Array failed (Parallel::UndumpableException)
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'Array#sort_by!'
        [...]
```

<details>
<summary>Full Backtrace</summary>

```
/.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'Enumerable#sort_by': ArgumentError: comparison of Array with Array failed (Parallel::UndumpableException)
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'Array#sort_by!'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'Enumerator#with_index'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:34:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'block in RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:109:in 'RBI::Visitor#visit_all'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:14:in 'RBI::Rewriters::SortNodes#visit'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/rewriters/sort_nodes.rb:117:in 'RBI::Tree#sort_nodes!'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/formatter.rb:54:in 'RBI::Formatter#format_tree'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/formatter.rb:44:in 'RBI::Formatter#format_file'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/formatter.rb:38:in 'RBI::Formatter#print_file'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/abstract_dsl.rb:219:in 'Tapioca::Commands::AbstractDsl#compile_dsl_rbi'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/abstract_dsl.rb:74:in 'block in Tapioca::Commands::AbstractDsl#generate_dsl_rbi_files'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/dsl/pipeline.rb:75:in 'block in Tapioca::Dsl::Pipeline#run'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:685:in 'Parallel.call_with_index'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:655:in 'Parallel.process_incoming_jobs'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:635:in 'block in Parallel.worker'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:626:in 'Process.fork'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:626:in 'Parallel.worker'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:617:in 'block in Parallel.create_workers'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:616:in 'Array#each'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:616:in 'Enumerable#each_with_index'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:616:in 'Parallel.create_workers'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:555:in 'Parallel.work_in_processes'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/parallel-2.0.1/lib/parallel.rb:302:in 'Parallel.map'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/executor.rb:23:in 'Tapioca::Executor#run_in_parallel'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'UnboundMethod#bind_call'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'block in Tapioca::Executor#_on_method_added'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/dsl/pipeline.rb:71:in 'Tapioca::Dsl::Pipeline#run'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'UnboundMethod#bind_call'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'block in Tapioca::Dsl::Pipeline#_on_method_added'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/abstract_dsl.rb:67:in 'Tapioca::Commands::AbstractDsl#generate_dsl_rbi_files'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'UnboundMethod#bind_call'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'block in Tapioca::Commands::AbstractDsl#_on_method_added'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/dsl_generate.rb:17:in 'Tapioca::Commands::DslGenerate#execute'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'UnboundMethod#bind_call'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'block in Tapioca::Commands::DslGenerate#_on_method_added'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/command.rb:27:in 'block in Tapioca::Commands::Command#run'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/runtime/helpers.rb:15:in 'block in Tapioca::Runtime.silence_warnings'
	from /.../ruby/4.0.2/lib/ruby/site_ruby/4.0.0/rubygems/user_interaction.rb:45:in 'Gem::DefaultUserInteraction.use_ui'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/runtime/helpers.rb:14:in 'Tapioca::Runtime.silence_warnings'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/commands/command.rb:26:in 'Tapioca::Commands::Command#run'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'UnboundMethod#bind_call'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/sorbet-runtime-0.6.13153/lib/types/private/methods/_methods.rb:261:in 'block in Tapioca::Commands::Command#_on_method_added'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/lib/tapioca/cli.rb:179:in 'Tapioca::Cli#dsl'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/thor-1.5.0/lib/thor/command.rb:28:in 'Thor::Command#run'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/thor-1.5.0/lib/thor/invocation.rb:127:in 'Thor::Invocation#invoke_command'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/thor-1.5.0/lib/thor.rb:538:in 'Thor.dispatch'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/thor-1.5.0/lib/thor/base.rb:585:in 'Thor::Base::ClassMethods#start'
	from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/tapioca-0.18.0/exe/tapioca:31:in '<top (required)>'
```
</details>

I assume this was introduced by 18687be448f18c51d17b0a87ebfe2f4ccc71b4fe.

I tried to debug it by printing out the arrays that are compared an noticed that the second array member sometimes was a symbol. So I added a `.to_s`:

https://github.com/Shopify/rbi/blob/086022edceff65969dc6bc5579943c4e89a9af8e/lib/rbi/rewriters/sort_nodes.rb#L35

=> 

```rb
[node_rank(n), node_name(n).to_s, i]
```

This now lead to a new error:

```
/.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:55:in 'String#<<': TypeError: no implicit conversion of Symbol into String (Parallel::UndumpableException)
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:55:in 'RBI::Printer#print'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:328:in 'RBI::Printer#visit_method'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:53:in 'RBI::Visitor#visit'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:90:in 'block in RBI::Printer#visit_all'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:89:in 'Array#each'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:89:in 'RBI::Printer#visit_all'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:625:in 'RBI::Printer#visit_group'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/visitor.rb:33:in 'RBI::Visitor#visit'
        from /.../ruby/4.0.2/lib/ruby/gems/4.0.0/gems/rbi-0.3.10/lib/rbi/printer.rb:90:in 'block in RBI::Printer#visit_all'
        [...]
```

... which could be fixed by this (wrong) workaround:

https://github.com/Shopify/rbi/blob/086022edceff65969dc6bc5579943c4e89a9af8e/lib/rbi/printer.rb#L55

=>

```rb
      @out << string.to_s
```

Now it generated rbi files without errors.

It looks like that somehow symbols end up in places where there shouldn't be any.

How can we debug this further?

- ruby 4.0.2
- tapioca (0.18.0)
- sorbet (0.6.13153)
- rbs (4.0.2)
- rbi (0.3.10)

### PR DESCRIPTION
**Pull request by KaanOzkan**
Resolves #593.

DSL compilers pass `Symbol` values to node constructors declared as `String`, which flows through and crashes `sort_nodes!` (Schwartzian sort can't compare String with Symbol) and `Printer` (`String#<<`).

Fix by coercing the type in the constructors using `name.to_s`.

Remove `attr_accessor :name` to prevent callers from passing symbol.

Second commit adds a contract test that auto-discovers every `Rewriters::*` class and runs each against a tree with Symbol-named nodes to guard against future regressions.

### CODE REVIEW

File: lib/rbi/model.rb [hunk 1]
```diff
@@ -196,12 +196,12 @@ def to_s
...
   class Module < Scope
     #: String
-    attr_accessor :name
+    attr_reader :name
 
     #: (String name, ?loc: Loc?, ?comments: Array[Comment]?) ?{ (Module node) -> void } -> void
     def initialize(name, loc: nil, comments: nil, &block)
       super(loc: loc, comments: comments) {}
-      @name = name
+      @name = name.to_s #: String
```
Comment (vinistock) [inline lib/rbi/model.rb:204]: Not a big deal, but considering that the `initialize` type if `String` and we made `name` read-only, do we also need to coerce?

Trying to instantiate this with a symbol should be a type checking error.

Comment (KaanOzkan) [reply lib/rbi/model.rb:204]: You're correct about callers with strict types but that doesn't cover every caller. Rest of the callers are fixed by the coercion. I went with this approach instead of ensuring every caller is passing a String. In this [issue](https://github.com/Shopify/rbi/issues/593) it was tapioca compilers passing Symbol but this is part of the public API and we can have other consumers that may incorrectly pass a Symbol.

Also since RBS comments aren't type checked at runtime a consumer can pass a symbol that is seen by the type checker as `T.untyped`. Or it could be that caller project isn't even using Sorbet.

Comment (vinistock) [reply lib/rbi/model.rb:204]: Yeah, fair.

**Review by vinistock — APPROVED** [review]
